from sys import argv

script, user_name = argv
prompt = '> '

print(f"Hi {user_name}, I'm the {script} script.")
print("I'd like to ask you a few questions.")
print(f"Do you like me {user_name}?")
likes = input(prompt)

print(f"Where do you live {user_name}?")
lives = input(prompt)

print("What kind of computer do you have?")
computer = input(prompt)

print(f"""
Alright, so you said {likes} about liking me.
You live in {lives}. Not sure where that is.
And you have a {computer} computer. Nice.
""")

'''Study Drill
#Zork and Adventure is a text based adventure games with prompts requesting the user to do actions

script, user_name, language = argv
filler = '****'

print(f"Hi {user_name}, I'm the {script} script.")
print("I'd like to ask you a few questions.")
print(f"Do you like me {user_name}?")
likes = input(prompt)

print(f"Where do you live {user_name}?")
lives = input(prompt)

print("What kind of computer do you have?")
computer = input(prompt)

print(f"Do you use that computer to program with {language}?")

print(f"""
Alright, so you said {likes} about liking me.
You live in {lives}. Not sure where that is.
And you have a {computer} computer and you know {language}. Nice.
""")
'''

'''Homework Assignment

script, name, spokenlanguage = argv
prompt = '>'

print(f"Hi {name}, I'm the {script} script.")
print("I'd like to ask you a few questions.")
print(f"Is {name} your first or last name?")
first_or_last = input(prompt)

print(f"Who named you {name}?")
namer = input(prompt)

print("What kind of music do you like?")
music = input(prompt)

print(f"Do you speak {spokenlanguage} at home? (do/don't)")
speak= input(prompt)

print(f"""
Alright, so you said your {first_or_last} name is {name}.
{namer} gave you your name and you speak {spokenlanguage}, which you {speak} speak at home.
You also like {music} music.
Autogenerated profile complete.
""")
'''